// <auto-generated />
using System;
using ChattyBot.Server.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChattyBot.Server.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChattyBotDbContext))]
    [Migration("20260509114115_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.FunFact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FunFacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Honey never spoils.\nArchaeologists have found edible honey in millennia-old Egyptian tombs!",
                            SourceUrl = "https://www.smithsonianmag.com/science-nature/the-science-behind-honeys-eternal-shelf-life-1218690/"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Venus is the only planet that rotates clockwise.\nIt spins in the opposite direction to most other planets in our solar system.",
                            SourceUrl = "https://science.nasa.gov/venus/facts/"
                        },
                        new
                        {
                            Id = 3,
                            Content = "The first 'computer bug' was an actual insect.\nIn 1947, engineers found a moth trapped in a relay of the Harvard Mark II computer.",
                            SourceUrl = "https://www.computerhistory.org/tdih/september/9/"
                        },
                        new
                        {
                            Id = 4,
                            Content = "The shortest war in history lasted only 38 minutes.\nThe Anglo-Zanzibar War occurred on August 27, 1896, between the UK and Zanzibar.",
                            SourceUrl = "https://www.historic-uk.com/HistoryUK/HistoryofBritain/The-Shortest-War-in-History/"
                        },
                        new
                        {
                            Id = 5,
                            Content = "Octopuses have three hearts.\nTwo pump blood to the gills, while the third pumps it to the rest of the body.",
                            SourceUrl = "https://www.newscientist.com/question/many-hearts-octopus/"
                        },
                        new
                        {
                            Id = 6,
                            Content = "France is the country with the most time zones in the world.\nIncluding its overseas territories, it covers a total of 12 different time zones.",
                            SourceUrl = "https://www.timeanddate.com/time/country-with-the-most-time-zones.html"
                        },
                        new
                        {
                            Id = 7,
                            Content = "Sloths can hold their breath longer than dolphins.\nBy slowing their heart rate, they can stay underwater for up to 40 minutes.",
                            SourceUrl = "https://www.bbc.co.uk/bitesize/articles/zqk4qyc"
                        },
                        new
                        {
                            Id = 8,
                            Content = "Koalas have fingerprints that are almost identical to humans.\nEven under a microscope, it’s difficult to distinguish them from human prints.",
                            SourceUrl = "https://www.pbs.org/wgbh/nova/article/koala-fingerprints/"
                        },
                        new
                        {
                            Id = 9,
                            Content = "It rains diamonds on Saturn and Jupiter.\nExtreme pressure turns atmospheric methane into soot, then graphite, and finally diamonds.",
                            SourceUrl = "https://www.bbc.com/news/science-environment-24477667"
                        },
                        new
                        {
                            Id = 10,
                            Content = "The 'smell of rain' is actually caused by bacteria and plants.\nIt’s called petrichor and is released from the soil when hit by raindrops.",
                            SourceUrl = "https://www.acs.org/content/dam/acsorg/education/students/highschool/chemistryclubs/infographics/petrichor-the-smell-of-rain.pdf"
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.Joke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jokes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "What did the shark say when he ate the clownfish?\nThis tastes a little funny."
                        },
                        new
                        {
                            Id = 2,
                            Content = "Why couldn’t the bad sailor learn the alphabet?\nBecause he always got lost at “C.”"
                        },
                        new
                        {
                            Id = 3,
                            Content = "What did one ocean say to the other ocean?\nNothing, they just waved."
                        },
                        new
                        {
                            Id = 4,
                            Content = "A Roman soldier walks into a bar, holds up two fingers and says:\n\"Five beers, please!\""
                        },
                        new
                        {
                            Id = 5,
                            Content = "I'm on a seafood diet.\nI see food and I eat it."
                        },
                        new
                        {
                            Id = 6,
                            Content = "How do you throw a space party?\nYou planet."
                        },
                        new
                        {
                            Id = 7,
                            Content = "The numbers 19 and 20 got into a fight.\n21."
                        },
                        new
                        {
                            Id = 8,
                            Content = "I’d tell you a pizza joke …\nbut it’s probably too cheesy."
                        },
                        new
                        {
                            Id = 9,
                            Content = "My grandpa always said when one door closes, another one opens.\nSmart man but a horrible cabinet maker."
                        },
                        new
                        {
                            Id = 10,
                            Content = "How many programmers does it take to change a light bulb?\nNone. They can't do it, that's a hardware problem!"
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.Meme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Memes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "/images/memes/meme1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "/images/memes/meme2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "/images/memes/meme3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "/images/memes/meme4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "/images/memes/meme5.jpg"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "/images/memes/meme6.jpg"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "/images/memes/meme7.jpg"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "/images/memes/meme8.jpg"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "/images/memes/meme9.jpg"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "/images/memes/meme10.jpg"
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Albert Einstein",
                            SourceUrl = "https://en.wikipedia.org/wiki/Albert_Einstein",
                            Text = "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Marcus Tullius Cicero",
                            SourceUrl = "https://en.wikipedia.org/wiki/Cicero",
                            Text = "A room without books is like a body without a soul."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mahatma Gandhi",
                            SourceUrl = "https://en.wikipedia.org/wiki/Mahatma_Gandhi",
                            Text = "Be the change that you wish to see in the world."
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mark Twain",
                            SourceUrl = "https://en.wikipedia.org/wiki/Mark_Twain",
                            Text = "If you tell the truth, you don't have to remember anything."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Oscar Wilde",
                            SourceUrl = "https://en.wikipedia.org/wiki/Oscar_Wilde",
                            Text = "To live is the rarest thing in the world. Most people exist, that is all."
                        },
                        new
                        {
                            Id = 6,
                            Author = "Martin Luther King Jr.",
                            SourceUrl = "https://en.wikipedia.org/wiki/Martin_Luther_King_Jr.",
                            Text = "Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that."
                        },
                        new
                        {
                            Id = 7,
                            Author = "Friedrich Nietzsche",
                            SourceUrl = "https://en.wikipedia.org/wiki/Friedrich_Nietzsche",
                            Text = "Without music, life would be a mistake."
                        },
                        new
                        {
                            Id = 8,
                            Author = "André Gide",
                            SourceUrl = "https://en.wikipedia.org/wiki/André_Gide",
                            Text = "It is better to be hated for what you are than to be loved for what you are not."
                        },
                        new
                        {
                            Id = 9,
                            Author = "Leslie Nielsen",
                            SourceUrl = "https://en.wikipedia.org/wiki/Leslie_Nielsen",
                            Text = "Doing nothing is very hard to do. You never know when you’re finished."
                        },
                        new
                        {
                            Id = 10,
                            Author = "Winston Churchill",
                            SourceUrl = "https://en.wikipedia.org/wiki/Winston_Churchill",
                            Text = "The price of greatness is responsibility."
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SongPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Queen",
                            Category = 0,
                            Description = "A six-minute suite notable for its lack of a refraining chorus, consisting of several sections: an intro, a ballad segment, an operatic passage, a hard rock part, and a reflective coda. It is one of the few progressive rock songs to become a global mainstream phenomenon.",
                            SongPath = "https://www.youtube.com/watch?v=fJ9rUzIMcZQ",
                            Title = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "AC/DC",
                            Category = 0,
                            Description = "Released in 1980 as a tribute to their late singer Bon Scott, this album marked the debut of Brian Johnson. It is one of the best-selling albums in history, featuring some of the most iconic guitar riffs ever recorded in hard rock.",
                            SongPath = "https://www.youtube.com/watch?v=pAgnJDJN4VA",
                            Title = "Back in Black"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Linkin Park",
                            Category = 0,
                            Description = "A defining song of the nu-metal era, featured on their debut album Hybrid Theory. The track is famous for the interplay between Chester Bennington's melodic vocals and Mike Shinoda's rap verses, reflecting on themes of failure and time.",
                            SongPath = "https://www.youtube.com/watch?v=eVTXPUF4Oz4",
                            Title = "In the End"
                        },
                        new
                        {
                            Id = 4,
                            Artist = "Metallica",
                            Category = 0,
                            Description = "A legendary power ballad released in 1991. Recognized as one of Metallica's most popular songs, it showcases a softer, more melodic side of the heavy metal giants and has become a staple in their live performances worldwide.",
                            SongPath = "https://www.youtube.com/watch?v=tAGnKpE4NCI",
                            Title = "Nothing Else Matters"
                        },
                        new
                        {
                            Id = 5,
                            Artist = "Michael Jackson",
                            Category = 1,
                            Description = "A revolutionary blend of post-disco, R&B, and funk. Released in 1983, it features one of the most recognizable basslines in music history and tells the story of a woman claiming the narrator is the father of her child.",
                            SongPath = "https://www.youtube.com/watch?v=Zi_XLOBDo_Y",
                            Title = "Billie Jean"
                        },
                        new
                        {
                            Id = 6,
                            Artist = "Taylor Swift",
                            Category = 1,
                            Description = "An uptempo dance-pop anthem released in 2014, marking Swift's full transition to pop music. The lyrics express indifference toward detractors and negative media scrutiny, set to a catchy drum beat and saxophone line.",
                            SongPath = "https://www.youtube.com/watch?v=nfWlot6h_JM",
                            Title = "Shake It Off"
                        },
                        new
                        {
                            Id = 7,
                            Artist = "Harry Styles",
                            Category = 1,
                            Description = "A synth-pop and new wave track released in 2022. The song features a nostalgic 80s-inspired sound and explores themes of personal transition and changing relationships, becoming a record-breaking global hit.",
                            SongPath = "https://www.youtube.com/watch?v=H5v3kku4y6Q",
                            Title = "As It Was"
                        },
                        new
                        {
                            Id = 8,
                            Artist = "Dua Lipa",
                            Category = 1,
                            Description = "A high-energy track that combines disco and dance-pop influences. Featured on the album Future Nostalgia, it uses outer space metaphors to describe the feeling of falling in love and became a defining hit of the early 2020s.",
                            SongPath = "https://www.youtube.com/watch?v=TUVcZfQe-Kw",
                            Title = "Levitating"
                        },
                        new
                        {
                            Id = 9,
                            Artist = "Miles Davis",
                            Category = 2,
                            Description = "A 1959 masterpiece and the quintessential example of modal jazz. Using the Dorian mode, the piece relies on melodic improvisation rather than complex chord changes, setting a new direction for modern jazz music.",
                            SongPath = "https://www.youtube.com/watch?v=ylXk1LBvIqU",
                            Title = "So What"
                        },
                        new
                        {
                            Id = 10,
                            Artist = "Louis Armstrong",
                            Category = 2,
                            Description = "First recorded in 1967, this song is a hopeful anthem about the beauty of the world and the future of humanity. Armstrong's gravelly, soulful voice turned the track into a timeless classic recognized by all generations.",
                            SongPath = "https://www.youtube.com/watch?v=rBrd_3VMC3c",
                            Title = "What a Wonderful World"
                        },
                        new
                        {
                            Id = 11,
                            Artist = "Louis Armstrong",
                            Category = 2,
                            Description = "The title song from the 1964 musical of the same name. Armstrong's rendition was a massive success, famously displacing the Beatles from the top of the charts and earning him multiple Grammy Awards.",
                            SongPath = "https://www.youtube.com/watch?v=Kx2AYFvwxKY",
                            Title = "Hello, Dolly!"
                        },
                        new
                        {
                            Id = 12,
                            Artist = "Eminem",
                            Category = 3,
                            Description = "A lyrical powerhouse released in 2013, famous for its speed and technical complexity. With 1,560 words, it entered the Guinness World Records for the most words in a hit single, showcasing Eminem's immense rapping skill.",
                            SongPath = "https://www.youtube.com/watch?v=XbGs_qK2PQA",
                            Title = "Rap God"
                        },
                        new
                        {
                            Id = 13,
                            Artist = "Kendrick Lamar",
                            Category = 3,
                            Description = "A hard-hitting call to humility released in 2017. Produced by Mike WiLL Made-It, the song features a minimalist, piano-driven beat and sharp lyrics that critiques modern ego and social media culture.",
                            SongPath = "https://www.youtube.com/watch?v=tvTRZJ-4EyI",
                            Title = "Humble"
                        },
                        new
                        {
                            Id = 14,
                            Artist = "The Notorious B.I.G.",
                            Category = 3,
                            Description = "Widely considered one of the greatest hip-hop tracks ever made. Released in 1994, it tells Biggie's 'rags-to-riches' story, sampling Mtume's 'Juicy Fruit' to create a smooth, soulful, and triumphant anthem.",
                            SongPath = "https://www.youtube.com/watch?v=_JZom_gVfuw",
                            Title = "Juicy"
                        },
                        new
                        {
                            Id = 15,
                            Artist = "2Pac",
                            Category = 3,
                            Description = "Perhaps the most famous diss track in history, recorded during the peak of the East Coast-West Coast rivalry. Released in 1996, the song contains vicious insults aimed primarily at The Notorious B.I.G. and Bad Boy Records.",
                            SongPath = "https://www.youtube.com/watch?v=41qC3w3UUkU",
                            Title = "Hit 'Em Up"
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.TriviaQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TriviaQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            CorrectAnswerIndex = 1,
                            Options = "[\"France\",\"Argentina\",\"Brazil\",\"Croatia\"]",
                            QuestionText = "Who won the 2022 FIFA World Cup?"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            CorrectAnswerIndex = 1,
                            Options = "[\"C. Ronaldo\",\"Lionel Messi\",\"Pele\",\"Ronaldinho\"]",
                            QuestionText = "Which player has the most Ballon d'Or awards?"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Italy\",\"Portugal\",\"Spain\",\"England\"]",
                            QuestionText = "In which country is the Santiago Bernabéu stadium located?"
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            CorrectAnswerIndex = 1,
                            Options = "[\"30\",\"45\",\"60\",\"90\"]",
                            QuestionText = "How many minutes does a standard half of football last?"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            CorrectAnswerIndex = 1,
                            Options = "[\"Zelda\",\"Link\",\"Ganon\",\"Navi\"]",
                            QuestionText = "Who is the main protagonist in 'The Legend of Zelda'?"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Nintendo\",\"Microsoft\",\"Sony\",\"Sega\"]",
                            QuestionText = "Which company launched the PlayStation console?"
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            CorrectAnswerIndex = 1,
                            Options = "[\"GTA V\",\"Minecraft\",\"Tetris\",\"Wii Sports\"]",
                            QuestionText = "What is the best-selling video game of all time?"
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            CorrectAnswerIndex = 0,
                            Options = "[\"Portal\",\"Half-Life\",\"BioShock\",\"Skyrim\"]",
                            QuestionText = "In which game does the phrase 'The cake is a lie' appear?"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Helium\",\"Oxygen\",\"Hydrogen\",\"Nitrogen\"]",
                            QuestionText = "What is the lightest chemical element?"
                        },
                        new
                        {
                            Id = 10,
                            Category = 2,
                            CorrectAnswerIndex = 1,
                            Options = "[\"Venus\",\"Mars\",\"Jupiter\",\"Saturn\"]",
                            QuestionText = "Which planet is known as the 'Red Planet'?"
                        },
                        new
                        {
                            Id = 11,
                            Category = 2,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Newton\",\"Tesla\",\"Einstein\",\"Hawking\"]",
                            QuestionText = "Who developed the Theory of Relativity?"
                        },
                        new
                        {
                            Id = 12,
                            Category = 2,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Iron\",\"Gold\",\"Mercury\",\"Lead\"]",
                            QuestionText = "Which metal is liquid at room temperature?"
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            CorrectAnswerIndex = 1,
                            Options = "[\"1987\",\"1989\",\"1991\",\"1993\"]",
                            QuestionText = "In which year did the Berlin Wall fall?"
                        },
                        new
                        {
                            Id = 14,
                            Category = 3,
                            CorrectAnswerIndex = 1,
                            Options = "[\"Buzz Aldrin\",\"Neil Armstrong\",\"Yuri Gagarin\",\"Michael Collins\"]",
                            QuestionText = "Who was the first person to walk on the moon?"
                        },
                        new
                        {
                            Id = 15,
                            Category = 3,
                            CorrectAnswerIndex = 0,
                            Options = "[\"Marie Antoinette\",\"Catherine de\\u0027 Medici\",\"Anne of Austria\",\"Mary, Queen of Scots\"]",
                            QuestionText = "Which French queen is famously associated with the phrase 'Let them eat cake'?"
                        },
                        new
                        {
                            Id = 16,
                            Category = 3,
                            CorrectAnswerIndex = 2,
                            Options = "[\"Romans\",\"Greeks\",\"Egyptians\",\"Mayans\"]",
                            QuestionText = "Which ancient civilization built the Great Pyramid of Giza?"
                        });
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvatarPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChattyBot.Server.Domain.Entities.VideoGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("VideoGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            Description = "Counter-Strike 2 is a 2023 free-to-play first-person shooter developed by Valve. As the fifth main entry in the series and an update to CS:GO, it pits Counter-Terrorists against Terrorists in intense, objective-based tactical combat.",
                            ImagePath = "/images/games/cs2.jpg",
                            Title = "Counter-Strike 2"
                        },
                        new
                        {
                            Id = 2,
                            Category = 0,
                            Description = "A legendary military shooter franchise published by Activision. Known for its fast-paced action and cinematic storytelling, the series spans from historical battles to futuristic warfare, including the latest Black Ops 7.",
                            ImagePath = "/images/games/call_of_duty.jpg",
                            Title = "Call of Duty"
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            Description = "Developed by DICE and EA, Battlefield focuses on large-scale multiplayer warfare. It emphasizes teamwork, combined arms combat involving vehicles, and fully destructible environments across massive maps.",
                            ImagePath = "/images/games/battlefield.jpg",
                            Title = "Battlefield"
                        },
                        new
                        {
                            Id = 4,
                            Category = 1,
                            Description = "A masterpiece by CD Projekt Red, this open-world RPG follows Geralt of Rivia, a monster hunter for hire. Based on Sapkowski's novels, it offers deep storytelling and a rich fantasy world explored from a third-person perspective.",
                            ImagePath = "/images/games/the_witcher_3.jpg",
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Description = "Directed by Hidetaka Miyazaki with worldbuilding by George R. R. Martin, Elden Ring is a challenging action RPG. Players explore the Lands Between on a quest to repair the Elden Ring and become the new Elden Lord.",
                            ImagePath = "/images/games/elden_ring.jpg",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Description = "Larian Studios' cinematic RPG set in the Dungeons & Dragons universe. Players lead a party of characters infected with Illithid parasites, offering unparalleled player freedom and deep turn-based tactical combat.",
                            ImagePath = "/images/games/baldurs_gate_3.jpg",
                            Title = "Baldur's Gate 3"
                        },
                        new
                        {
                            Id = 7,
                            Category = 2,
                            Description = "A 2018 action-adventure game that reimagines Kratos' journey. Now set in the realm of Norse mythology, Kratos must navigate a dangerous world with his son Atreus, blending visceral combat with an emotional father-son story.",
                            ImagePath = "/images/games/god_of_war.jpg",
                            Title = "God of War"
                        },
                        new
                        {
                            Id = 8,
                            Category = 2,
                            Description = "Set in the Wild West in 1899, it follows Arthur Morgan, a member of the Van der Linde gang, as he struggles to survive in a changing world. The game features an open world where players can explore, fight, rob, and hunt.",
                            ImagePath = "/images/games/red_dead_redemption_2.jpg",
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 9,
                            Category = 2,
                            Description = "Created by Naughty Dog, this post-apocalyptic series follows survivors Joel, Ellie, and Abby. It is renowned for its intense third-person combat, stealth mechanics, and a hauntingly beautiful, character-driven narrative.",
                            ImagePath = "/images/games/the_last_of_us.jpg",
                            Title = "The Last of Us"
                        },
                        new
                        {
                            Id = 10,
                            Category = 3,
                            Description = "Microsoft's longest-running software line and a pioneer in flight simulation. It allows players to pilot highly detailed aircraft across a realistic, 1:1 scale representation of the entire planet using satellite data.",
                            ImagePath = "/images/games/microsoft_flight_simulator.jpg",
                            Title = "Microsoft Flight Simulator"
                        },
                        new
                        {
                            Id = 11,
                            Category = 3,
                            Description = "A world-renowned life simulation series developed by Maxis. Players create 'Sims', build their homes, and manage their daily lives, careers, and relationships in one of the best-selling video game franchises ever.",
                            ImagePath = "/images/games/the_sims.jpg",
                            Title = "The Sims"
                        },
                        new
                        {
                            Id = 12,
                            Category = 3,
                            Description = "Developed by GIANTS Software, this series offers a realistic deep dive into modern agriculture. Players manage farms, breed livestock, and operate hundreds of authentic vehicles from real-world farming brands.",
                            ImagePath = "/images/games/farming_simulator.jpg",
                            Title = "Farming Simulator"
                        },
                        new
                        {
                            Id = 13,
                            Category = 3,
                            Description = "A highly popular truck simulator by SCS Software. Players travel across a vast map of Europe, delivering cargo in various trucks while managing their own logistics company and expanding their fleet.",
                            ImagePath = "/images/games/euro_truck_simulator_2.jpg",
                            Title = "Euro Truck Simulator 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
